from ECTools import Point,ECCurve,ECGroup,ECFactory

if __name__ == '__main__':

    factory = ECFactory()

    factory.print_all_groups(ECGroup(11),ECCurve(0,7))              # print all groups generated by ECCurve with valid origin 
    factory.print_group(ECGroup(11),ECCurve(0,7),Point(7,3))       # print generated group by ECCurve for a given origin (7,3)
    factory.plot_group(ECGroup(11),ECCurve(0,7),Point(7,3))  # plot graph : blocking call (need to close window)

    #factory.print_all_groups(ECGroup(31),ECCurve(0,7))              # print all groups generated by ECCurve with valid origin 
    #factory.print_group(ECGroup(31),ECCurve(0,7),Point(25,16))       # print generated group by ECCurve for a given origin (25,16)
    #factory.plot_group(ECGroup(31),ECCurve(0,7),Point(25,16))  # plot graph : blocking call (need to close window)


